apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    metadata:
      name: migrate
      annotations:
        checksum/goose-config: {{ include "cfssl/templates/migrate-dbconf-template-configmap.yaml" . | sha256sum }}
        checksum/goose-migrations: {{ include "cfssl/templates/database-migrations-configmap.yaml" . | sha256sum }}
      labels:
        app: cfssl
        service: migrate
    spec:
      containers:
      - name: initdb
        image: "{{ .Values.containers.cfssl.image.repository }}:{{ .Values.containers.cfssl.image.tag }}"
        imagePullPolicy: {{ .Values.containers.cfssl.image.pullPolicy }}
        command: ["/bin/sh", "-c", "/init/migrate.sh"]
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretsRef }}
              key: secret-postgresql-postgres-user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretsRef }}
              key: secret-postgresql-postgres-password
        volumeMounts:
          - name: init
            mountPath: /init
          - name: workingdir
            mountPath: /goose-config/
          - name: db-migrations
            mountPath: /goose-config/migrations
      volumes:
        - name: init
          configMap:
            name: migrate-bootstrap
            defaultMode: 0755
            items:
            - key: migrate.sh
              path: migrate.sh
        - name: workingdir
          emptyDir: {}
        - name: db-migrations
          configMap:
            name: database-migrations
            items:
            - key: 001_CreateCertificates.sql
              path: 001_CreateCertificates.sql
      restartPolicy: Never
