apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: initial-cert-store
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}