apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-init
data:
  init.sh: |
    #! /bin/sh
    # substitute secrets in db DSN
    echo "writing DB DSN config file"
    mkdir /goose-init
    cat << EOF > /goose-init/dbconf.yml
    deploy:
      driver: postgres
      open: user=${DATABASE_USERNAME} password=${DATABASE_PASSWORD} host=postgresql dbname=cfssl sslmode=disable
    EOF
    echo "fetching goose"
    # get goose, then run it
    /usr/local/go/bin/go get -u bitbucket.org/liamstask/goose/cmd/goose
    echo "copying migrations to /goose-init/"
    cp -r $GOPATH/src/github.com/cloudflare/cfssl/certdb/pg/migrations /goose-init/
    echo "running goose up"
    /go/bin/goose -env deploy -path /goose-init/ up
