apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-init
data:
  init.sh: |
    #! /bin/sh
    # substitute secrets in db DSN
    mkdir /goose-init
    cat << EOF > /goose-init/dbconf.yml
    deploy:
    driver: postgres
    open: user=${DATABASE_USERNAME} password=${DATABASE_PASSWORD} host=postgresql dbname=cfssl sslmode=disable
    EOF
    chmod +x /goose-init/dbconf.yaml
    # get goose, then run it
    /usr/local/go/bin/go get -u github.com/steinbacher/goose/cmd/goose
    cp -r $GOPATH/src/github.com/cloudflare/cfssl/certdb/pg/migrations /goose-config/
    /go/bin/goose -env deploy -path /goose-init/ up
