# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
kubecontext: cluster
containers:
  postgresql:
    image:
      repository: downup/postgres
      tag: 9.5.6
      pullPolicy: IfNotPresent
resources:
  postgresql:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 8Mi
monitoring:
  probe_services: true
alerting:
  chat_channels: alerts
  paging_profiles: 24x7
metrics:
  scrape_prometheus: true
  prometheus_port: 9145
services:
  db:
    type: ClusterIP
    externalPort: 5432
    internalPort: 5432
persistence:
  enabled: true
  size: 256Mi
  storageClass: default
secretsRef: "__required__"
