apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}"
    app: nginx
    service: http
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ template "globalDeploymentRevisionHistory" . }}
  selector:
    matchLabels:
      chart: "{{ .Chart.Name }}"
      app: nginx
      service: http
  template:
    metadata:
      labels:
        chart: "{{ .Chart.Name }}"
        app: nginx
        service: http
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.containers.nginx.image.repository }}:{{ .Values.containers.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.containers.nginx.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.nginx.internalPort }}
          name: https
          protocol: TCP
        - containerPort: {{ .Values.services.metrics.internalPort }}
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.services.nginx.internalPort }}
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.services.nginx.internalPort }}
            scheme: HTTPS
        resources:
{{ toYaml .Values.resources | indent 12 }}
