apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: nginx
    service: http
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.containers.nginx.image.repository }}:{{ .Values.containers.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.containers.nginx.image.pullPolicy }}
        command: ["sleep", "999999"]
        ports:
        - containerPort: {{ .Values.services.nginx.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.nginx.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.nginx.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
