apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: nginx
    service: http
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ template "globalDeploymentRevisionHistory" . }}
  selector:
    matchLabels:
      chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      app: nginx
      service: http
  template:
    metadata:
      annotations:
        alert-chat-channels: {{ .Values.alerting.chat_channels | quote }}
        alert-paging-profiles: {{ .Values.alerting.paging_profiles | quote }}
      labels:
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        app: nginx
        service: http
    spec:
      initContainers:
{{ include "common.certificate_init_container.container" . | indent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.containers.nginx.image.repository }}:{{ .Values.containers.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.containers.nginx.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.nginx.internalPort }}
          name: https
          protocol: TCP
        - containerPort: {{ .Values.services.metrics.internalPort }}
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.services.nginx.internalPort }}
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.services.nginx.internalPort }}
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
{{ toYaml .Values.containers.nginx.resources | trim | indent 10 }}
        volumeMounts:
        - mountPath: /usr/local/openresty/nginx/ssl
          name: certificate-init-container-workdir
          readOnly: true
      volumes:
{{ include "common.certificate_init_container.volume" . | indent 8 }}
