apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: nginx
    service: http
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ template "globalDeploymentRevisionHistory" . }}
  selector:
    matchLabels:
      chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      app: nginx
      service: http
  template:
    metadata:
      annotations:
        alert-chat-channels: {{ .Values.alerting.chat_channels | quote }}
        alert-paging-profiles: {{ .Values.alerting.paging_profiles | quote }}
        checksum/init-setup: {{ include (print $.Template.BasePath "/init-setup-configmap.yaml") . | sha256sum }}
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "gen-csr",
                "image": "{{ .Values.containers.cfssl.image.repository }}:{{ .Values.containers.cfssl.image.tag }}",
                "imagePullPolicy": "{{ .Values.containers.cfssl.image.pullPolicy }}",
                "command": ["/pre-secrets/gen-csr.sh"],
                "workingDir": "/tls-workdir",
                "volumeMounts": [
                  {
                    "name": "pre-secrets",
                    "mountPath": "/pre-secrets"
                  },
                  {
                    "name": "tls-workdir",
                    "mountPath": "/tls-workdir"
                  }
                ],
                "resources": {{ toJson .Values.containers.cfssl.resources }}
            },
            {
                "name": "csr-submit",
                "image": "{{ .Values.containers.cfssl.image.repository }}:{{ .Values.containers.cfssl.image.tag }}",
                "imagePullPolicy": "{{ .Values.containers.cfssl.image.pullPolicy }}",
                "command": ["/pre-secrets/csr-submit.sh"],
                "workingDir": "/tls-workdir",
                "command": ["sleep", "999999"],
                "volumeMounts": [
                  {
                    "name": "pre-secrets",
                    "mountPath": "/pre-secrets"
                  },
                  {
                    "name": "tls-workdir",
                    "mountPath": "/tls-workdir"
                  }
                ],
                "resources": {{ toJson .Values.containers.cfssl.resources }}
            }
        ]'
      labels:
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        app: nginx
        service: http
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.containers.nginx.image.repository }}:{{ .Values.containers.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.containers.nginx.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.nginx.internalPort }}
          name: https
          protocol: TCP
        - containerPort: {{ .Values.services.metrics.internalPort }}
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.services.nginx.internalPort }}
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.services.nginx.internalPort }}
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
{{ toYaml .Values.containers.nginx.resources | indent 12 }}
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: tls-workdir
          readOnly: true
      volumes:
        - name: pre-secrets
          configMap:
            name: init-setup
            defaultMode: 0755
            items:
            - key: gen-csr.sh
              path: gen-csr.sh
            - key: csr-submit-{{ .Values.pki.ca_type }}.sh
              path: csr-submit.sh
            - key: csr-retrieve-{{ .Values.pki.ca_type }}.sh
              path: csr-retrieve.sh
        - name: tls-workdir
          emptyDir: {}