apiVersion: v1
kind: Service
metadata:
  name: http
  annotations:
    prometheus.io/probe: {{ .Values.monitoring.probe_services | quote }}
    alert-chat-channels: {{ .Values.alerting.chat_channels | quote }}
    alert-paging-profiles: {{ .Values.alerting.paging_profiles | quote }}
  labels:
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: nginx
    service: http
spec:
  type: {{ .Values.services.type }}
  ports:
  - name: http
    port: {{ .Values.services.nginx.externalPort }}
    targetPort: {{ .Values.services.nginx.internalPort }}
    protocol: TCP
  selector:
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: nginx
    service: http
