kind: Service
apiVersion: v1
metadata:
  name: openvpn
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    service: openvpn
spec:
  ports:
    - name: openvpn
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: {{ .Values.openvpn.OVPN_PROTO | upper }}
  selector:
    app: openvpn
    service: openvpn
  type: {{ .Values.service.type }}