kind: Service
apiVersion: v1
metadata:
  name: openvpn
  labels:
    app: openvpn
    service: openvpn
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
    - name: openvpn
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: {{ .Values.openvpn.OVPN_PROTO | upper }}
  selector:
    app: openvpn
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    service: openvpn
  type: {{ .Values.service.type }}