apiVersion: v1
description: A Helm chart for Kubernetes
name: postgresql
version: 0.1.1
home: https://postgresql.org
maintainers:
- email: shane.ramey@gmail.com
  name: Shane Ramey
sources:
- https://hub.docker.com/_/postgres/
