replicaCount: 1
kubecontext: cluster
containers:
  postgresql:
    image:
      repository: us.gcr.io/downup-164000/postgres
      tag: 9.5.6
      pullPolicy: IfNotPresent
  postgresql_exporter:
    image:
      repository: wrouesnel/postgres_exporter
      tag: v0.1.1
      pullPolicy: IfNotPresent
resources:
  postgresql:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 8Mi
  postgresql_exporter:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 256Mi
monitoring:
  probe_services: true
alerting:
  chat_channels: alerts
  paging_profiles: 24x7
metrics:
  scrape_prometheus: true
  prometheus_port: 9145
  postgresql_exporter:
    enabled: false
services:
  db:
    type: ClusterIP
    externalPort: 5432
    internalPort: 5432
persistence:
  enabled: true
  size: 256Mi
  storageClass: standard
secretsRef: "__required__"
