apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  labels:
    app: kibana-logging
    service: http
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
  annotations:
    alert-chat-channels: {{ .Values.alerting.chat_channels | quote }}
    alert-paging-profiles: {{ .Values.alerting.paging_profiles | quote }}
spec:
  ports:
  - port: {{ .Values.services.kibana.externalPort }}
    protocol: TCP
    targetPort: ui
  selector:
    app: kibana-logging
    service: http