# Default values for kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Special values:
# - kubecontext changed by override on-the-fly for downward-API like function
# - configs - overridden by confd values.configs.yaml (via Makefile)
# - secrets - overridden by confd values.secrets.yaml (via Makefile)
kubecontext: cluster
services:
  type: ClusterIP
  kibana:
    externalPort: 5601
    internalPort: 5601
  nginx:
    externalPort: 443
    internalPort: 443
  metrics:
    internalPort: 9145
containers:
  kibana:
    image:
      repository: gcr.io/google_containers/kibana
      tag: v4.6.1-1
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
monitoring:
  probe_services: true
alerting:
  chat_channels: alerts
  paging_profiles: 24x7
metrics:
  scrape_prometheus: true
  prometheus_port: 9145
configs:
secrets:
