apiVersion: v1
kind: Secret
metadata:
  name: nginx-tls
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  vault.crt: |
    {{ .Values.secrets.vault.server_tls_cert | b64enc }}
  vault.key: |
    {{ .Values.secrets.vault.server_tls_key | b64enc }}
