kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: run-nfs-provisioner
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: nfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
