kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-provisioner
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: nfs-provisioner
    service: nfs
  annotations:
    pod.alpha.kubernetes.io/initialized: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        app: nfs-provisioner
        service: nfs
    spec:
      serviceAccount: nfs-provisioner
      terminationGracePeriodSeconds: 0
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
          - name: rpcbind-udp
            containerPort: 111
            protocol: UDP
        securityContext:
          capabilities:
            add:
              - DAC_READ_SEARCH
        args:
          - "-provisioner=downup.us/nfs"
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SERVICE_NAME
            value: nfs-provisioner
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: export-volume
            mountPath: /export
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: export-volume
          hostPath:
            path: {{ .Values.hostPath }}
