kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: nfs-provisioner
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: {{ .Values.defaultStorageClass | quote }}
provisioner: downup.us/nfs
