apiVersion: v1
kind: Service
metadata:
  name: http
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    service: http
spec:
  type: {{ .Values.services.service1.type }}
  ports:
  - port: {{ .Values.services.service1.externalPort }}
    targetPort: {{ .Values.services.service1.internalPort }}
    protocol: TCP
    name: {{ .Values.services.service1.name }}
  selector:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    service: http
