apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: postgresql
    service: database
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql
    service: database
  sessionAffinity: None
  type: ClusterIP
