dependencies:
  - name: django
    version: 0.1.0
    repository: http://charts.downup.us
  - name: nginx
    version: 0.1.0
    repository: http://charts.downup.us
  - name: redis
    version: 0.1.0
    repository: http://charts.downup.us
  - name: postgres
    version: 0.1.0
    repository: http://charts.downup.us

