# Default values for elasticsearch-logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Special values:
# - kubecontext changed by override on-the-fly for downward-API like function
# - configs - overridden by confd values.configs.yaml (via Makefile)
# - secrets - overridden by confd values.secrets.yaml (via Makefile)
kubecontext: cluster
replicaCount: 3
services:
  type: ClusterIP
  elasticsearch:
    externalPort: 9200
    internalPort: 9200
  estransport:
    internalPort: 9300
  nginx:
    externalPort: 443
    internalPort: 443
  metrics:
    internalPort: 9145
containers:
  elasticsearch:
    image:
      repository: gcr.io/google_containers/elasticsearch
      tag: v2.4.1-1
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 200Mi
  nginx:
    image:
      repository: nginx-prom
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 32Mi
      requests:
        cpu: 10m
        memory: 10Mi
persistence:
  enabled: 'true'
  pv1:
    accessMode: ReadWriteOnce
    size: 32Gi
    storageClass: example-nfs
monitoring:
  probe_services: true
alerting:
  chat_channels: alerts
  paging_profiles: 24x7
metrics:
  scrape_prometheus: true
  prometheus_port: 9145
secrets:
  nginx:
    server_tls_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ3akNDQXRhZ0F3SUJBZ0lKQU1ocEJFQlA0OGI3TUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdMTVFzd0NRWUQKVlFRR0V3SlZVekVUTUJFR0ExVUVDQXdLUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnd3TlUyRnVJRVp5WVc1agphWE5qYnpFaE1COEdBMVVFQ2d3WVNXNTBaWEp1WlhRZ1YybGtaMmwwY3lCUWRIa2dUSFJrTVJjd0ZRWURWUVFMCkRBNUpibVp5WVhOMGNuVmpkSFZ5WlRFVE1CRUdBMVVFQXd3S2RHVnpkQzVzYjJOaGJEQWVGdzB4TnpBek1ESXcKT1RBNU1qZGFGdzB4T0RBek1ESXdPVEE1TWpkYU1JR0xNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUdBMVVFQ0F3SwpRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6RWhNQjhHQTFVRUNnd1lTVzUwClpYSnVaWFFnVjJsa1oybDBjeUJRZEhrZ1RIUmtNUmN3RlFZRFZRUUxEQTVKYm1aeVlYTjBjblZqZEhWeVpURVQKTUJFR0ExVUVBd3dLZEdWemRDNXNiMk5oYkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQUtrVmFpc3FYT1FvTXd1VXlvc2JtM0RMcm5naXRqMXBZbDBqVjE5SG0vRFhkbmZkOHN5RndTdU5qenZ6CktHR2ZzMXpMUERZVkE2ZGhDT2c1bHRtdkhqYURNTWJsRFgxdDhjdTBuTDhDcnB2aVIwZzdJa3BtS1VNT243NzIKeUVQT1o0M0RCWktZQ0JPWTZXWGdZblV2WFBuYXlrTlB1aHNBUll6NkhSTjdDUE5aTE02alVTa040Y213WHFhNgpXUlJEYUg4UmhweTFaZCtDSGRuYzVPa3NGM3kyc2xxdkhnbStOMFFmNVZPdG9TVnQ0RDBYS01CS3RFdHdMeG9OCjlnc09EMVJLT3NjblBLalJ3cVZIWHRIc1JqeVgzVDROaTJPTjByVGZmbDM0eXdUT1BWdHoxYTkxRzZPVFBJdW8KaHJBRFljeEVuaERtVDRnOEpFeHQrcjlHVDk4Q0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZEYjJRaVdjYnI5bAp6Y1ZoZUxqcHBUd3NwWXpyTUI4R0ExVWRJd1FZTUJhQUZEYjJRaVdjYnI5bHpjVmhlTGpwcFR3c3BZenJNQThHCkExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUJwZXh5Rmk2eGROTFdzV3dmaDQKSTdBZk1aUnJkYnp6U1oxMnBkRThGRElnMVcwWFZtSGFUNGs3cFUwbmdHVzM5TU1GM3E4dTYvTndMZ1AwNkN1TAordXR1YXg1cVJtQ00zS04zNDBkTURBSElJL05hbEEzNGdUSVV4SWYxWnRTL2ZKYXNBUlpWaUlwNC9SOU8wampVCmtMaXREMmc5VjJabVVSTHZqRG9qYmV6N3ZFcHFCeGRFbHErRitPTkdDcmEzeWlubVd2YU1BenZsQWZXVXJsRUgKU1B2dDFPc1l3WFRnbWNQekwwdFJYNmlCOVcxS1p3Q1NkdVlxTmxyalRoZHhuVUhLYlpqUzZYRmNzT3gxdEFFQwpOWHRrcXIwY0ZFMEl5enFiRitldnQ1ZTIyQnA0bzd5ZWZiVVJPTEo5bTlnc0Q1V1hseVd3Q0lNQ1U3MHFKTW8vCkh5Zz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server_tls_key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3BGV29yS2x6a0tETUwKbE1xTEc1dHd5NjU0SXJZOWFXSmRJMWRmUjV2dzEzWjMzZkxNaGNFcmpZODc4eWhobjdOY3l6dzJGUU9uWVFqbwpPWmJacng0Mmd6REc1UTE5YmZITHRKeS9BcTZiNGtkSU95SktaaWxERHArKzlzaER6bWVOd3dXU21BZ1RtT2xsCjRHSjFMMXo1MnNwRFQ3b2JBRVdNK2gwVGV3anpXU3pPbzFFcERlSEpzRjZtdWxrVVEyaC9FWWFjdFdYZmdoM1oKM09UcExCZDh0ckphcng0SnZqZEVIK1ZUcmFFbGJlQTlGeWpBU3JSTGNDOGFEZllMRGc5VVNqckhKenlvMGNLbApSMTdSN0VZOGw5MCtEWXRqamRLMDMzNWQrTXNFemoxYmM5V3ZkUnVqa3p5THFJYXdBMkhNUko0UTVrK0lQQ1JNCmJmcS9Say9mQWdNQkFBRUNnZ0VBRUQwRVF6MEFTdEVwaGRVMlZvSENQZVR4em92VzRMTDhSV0dkaElNR0VPMUEKYldhZGFOTDNxRTBpRW1uWjJQWlRiWGYvUWxwbVRXN2VRaDgxdzVZejJweGkxTmN1b25zcW01dXU2aEZCMzZxdAptZHhFQU0wcTdVdThQOFRIbXV0NXVuMmVUV1BZY3JsZXdPLzV4TE5WeEpFa2w2NVNlMEZkYkpxZ3JEeEdzY2dZCnF5RUxUNzhoM2JkWUxxTzVYNlJDN0hqS2xtZ1lNeXRkMkpEWXdqNkhkc2FiaXo3RFFDUysrWlhxcGxFVnl1MVMKcTl1c0dxY3JQYkpxZkhWS1FQWlNJM0FLWXlxSjJYS09lU1YxUHE0bWRneUNnSlFKT3ZhNzBya0xSU25paFE5RQpVK2dVQVRmUDFJNEVLQUVrVDRpVjBGQ3ZZdjhpMnZnU3hZRlpzZVBFMFFLQmdRRFpnNEZEbTNZZTFxSWVoaGxYCjNHYTVNaWs0NU9CbDB6cmZrRmEzZlQ4T3ZXeVhVVU04U3FTVWpZVkEydHNJUTlrblBGdVR2SUtHZDk1YmgzS0IKSWpselNwNXltT0ZCdzdEbzAwOXJOTGZaazdLQkJKUG9wNGY0eDRqSktxUVNwMzZaOVRZWnZiL1RjditpbHJuRAorOU9yQVAzWUkyN041YUQ1amlna1VBcTNHd0tCZ1FESEFEbE00L2N5bXROd3hoZmFSMVUzN3lBbFp3YkNsRThDCjZBcTRQTEVzcGxBY3dFY1h1V2Z0ZFQ3MFdIVUxGNkdzV0pMbzg3UnFlZkJZTnZBY093eWM4VUp4dmFhcEpEekIKbHowVXQ0RXJmaEZZdzMvb1B1bUNxZDNUZEFsUzk2SzRBNHpqZ2ZIREFtQ21LSFE5R3FYR2llOHNtZElOVGVMRApYakpZeUtmQ2pRS0JnUUNkR1ZQMVpvVXJ4TTJXeWpmbnMzSWw5RXE5b3VGSDZnWXRqbXh6WG14NjB1bHBhUEhzCnkrU092cUF0dFdSWlZkZXpkTzZYaDZHbVNWRTZQbHUvVk42MW5JRlFONGNLSHJMWmxqVllNdDFPc2xSTXh1ZWwKTThzTExlSm5tUHFqMW9HajVPMU1MallzSEhUeUUzYmNURGdXM0VKN0p5eFNYYldrU0w1SmE5NHhYUUtCZ0J0cgpWbm5YdDBuTHQzS0VlT2praDBOcnVWd3Q4K3Ava050dnFYcDFNbHhhbGhOQUV3dWJ5a3dYcVpMMVZUc3dDR0M4CjI1RXBjeVJ3cE1NaTNyYWxGRG5UckRvTHpaamttMUo1U2pzK2haZStpUmxYNXBuVGdVMDFwcERxSGhiR2RDOHkKbmdrQzhKTFVFd2tSN2VJMWQ3NEJaMmtYMEs5d21kd2RjSVozTDFaSkFvR0JBTFF3UEdvZ3ZRTWt0ZFByM3c2ZQpBVUU1WFhsYlFBWFBGajRZeG0zK01qOGErNTJBcmw3TFVEODRMNnc2bmpLTEtvRm5YN0ZDODRQbUNlUFQ2azBjCkVmbDAvNUtrNjhVcWlwQlhXWjY1MjJBRmQzWktFZG9qTk1FSnFaYXJWQlBhaHFYVExXdUVGbG02Q0hvV2RiMVUKQjN3TEU0ZlA4bmpWcy9GdGNIUytVNUozCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
