# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
kubecontext: cluster
replicaCount: 1
containers:
  nginx:
    image:
      repository: us.gcr.io/downup-164000/nginx
      tag: 781280cd1e86663ad60bf3a12c8a9befa6059cb0
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 32Mi
      requests:
        cpu: 100m
        memory: 10Mi
services:
  nginx:
    type: ClusterIP
    externalPort: 443
    internalPort: 443
  metrics:
    internalPort: 9145
monitoring:
  probe_services: true
alerting:
  chat_channels: alerts
  paging_profiles: 24x7
metrics:
  scrape_prometheus: true
  prometheus_port: 9145

