# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
containers:
  cfssl:
    image:
      repository: us.gcr.io/downup-164000/cfssl
      tag: 1.2.0
      pullPolicy: IfNotPresent
    resources: # FIXME: apply these in deployment
      limits:
        cpu: 100m
        memory: 32Mi
      requests:
        cpu: 100m
        memory: 10Mi
  nginx:
    image:
      repository: us.gcr.io/downup-164000/nginx
      tag: 0b2bb9eec079ebdf1b620484b45b2332cac47be1
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 32Mi
      requests:
        cpu: 100m
        memory: 10Mi
services:
  nginx:
    type: ClusterIP
    externalPort: 443
    internalPort: 443
  metrics:
    internalPort: 9145
monitoring:
  probe_services: true
alerting:
  chat_channels: alerts
  paging_profiles: 24x7
metrics:
  scrape_prometheus: true
  prometheus_port: 9145

