apiVersion: v1
description: A Helm chart for Kubernetes
name: cfssl
version: 0.1.85
home: http://charts.downup.us/cfssl
maintainers:
- email: shane.ramey@gmail.com
  name: Shane Ramey
sources:
- https://github.com/cloudflare/cfssl
