apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-es
  labels:
    app: fluentd
    service: fluentd
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      app: fluentd
      service: fluentd
  template:
    metadata:
      annotations:
        alert-chat-channels: {{ .Values.alerting.chat_channels | quote }}
        alert-paging-profiles: {{ .Values.alerting.paging_profiles | quote }}
      labels:
        app: {{ .Chart.Name }}
        service: fluentd
    spec:
      containers:
      - name: fluentd-es
        image:  "{{ .Values.containers.fluentd.image.repository }}:{{ .Values.containers.fluentd.image.tag }}"
        imagePullPolicy:  {{ .Values.containers.fluentd.image.pullPolicy }}
        command:
          - '/bin/sh'
          - '-c'
          - '/usr/sbin/td-agent 2>&1 >> /var/log/fluentd.log'
        # env:
        # - name: ELASTICSEARCH_HOST
        #   value: elasticsearch-logging
        # - name: KUBERNETES_URL
        #   value: https://kubernetes.default.svc.downup.local
        resources:
          limits:
            cpu: {{ .Values.containers.fluentd.resources.limits.cpu }}
            memory: {{ .Values.containers.fluentd.resources.limits.memory }}
          requests:
            cpu: {{ .Values.containers.fluentd.resources.requests.cpu }}
            memory: {{ .Values.containers.fluentd.resources.requests.memory }}
        volumeMounts:
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
