apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-nginx
data:
  nginx-site: |2

        server {
            listen 443 default_server ssl;
            server_name _;

            add_header      Cache-Control max-age=0;

            root /var/www/html;
            index index.html index.htm;

            ssl on;
            ssl_certificate /etc/nginx/ssl/certificate.crt;
            ssl_certificate_key /etc/nginx/ssl/certificate.key;
            ssl_session_timeout 1d;
            ssl_session_cache shared:SSL:50m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2;
            ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;
            ssl_prefer_server_ciphers on;

            location ~ /ping$ {
                access_log off;
                return 200;
            }
            location / {
              return 200;
            }

        }

        server {
          listen 9145;
          allow all;
          location /metrics {
            access_log off;
            content_by_lua 'prometheus:collect()';
          }
        }