apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.postgresPassword }}
  secret-postgresql-postgres-password:  {{ .Values.postgresPassword | b64enc | quote }}
  {{ else }}
  secret-postgresql-postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}