# Default values for http-starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas:
  httpCount: 1
  postgresCount: 1
kubecontext: cluster
containers:
  container1:
    image:
      repository: image1
      tag: 0.1.0
      pullPolicy: IfNotPresent
  container2:
    image:
      repository: image2
      tag: 0.1.0
      pullPolicy: IfNotPresent
resources:
  container1:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 8Mi
  container2:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 8Mi
monitoring:
  probe_services: true
alerting:
  chat_channels: alerts
  paging_profiles: 24x7
metrics:
  scrape_prometheus: true
  prometheus_port: 9145
services:
  service1:
    type: ClusterIP
    externalPort: 443
    internalPort: 443
  service2:
    type: ClusterIP
    externalPort: 5432
    internalPort: 5432
persistence:
  container1:
    volume1:
    - size: 256Mi
      storageClass: standard
    volume2:
    - size: 256Mi
      storageClass: standard
  container2:
    volume1:
    - size: 256Mi
      storageClass: standard
    volume2:
    - size: 256Mi
      storageClass: standard
secretsRef: "__required__"
configs:
  container1:
    setting1: some
    setting2: values
