apiVersion: v1
kind: Service
metadata:
  name: http
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    service: http
spec:
  type: {{ .Values.services.nginx.type }}
  ports:
  - name: nginx
    port: {{ .Values.services.nginx.externalPort }}
    targetPort: {{ .Values.services.nginx.internalPort }}
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    service: http
